#
# Splunk app configuration file
#

[install]
is_configured = 0

[ui]
is_visible = true
label = SOC Central Monitoring App

[launcher]
author = Crossrealms, Inc. - Partner, an official Splunk Partner
description = 
version = 1.0.0

