[scm_lookup_environment(1)]
args = input_field
definition = lookup environment_mapping host_name as "$input_field$" OUTPUT environment | eval environment=coalesce(environment, '$input_field$')
iseval = 0

[scm_lookup_environment]
definition = lookup sak_environments host_name as splunk_server OUTPUT environment | eval environment=coalesce(environment, splunk_server)
iseval = 0

[scm_cyences_index]
definition = index IN ("cyences")
