# For GitHub Pages
# Comment out for local development
remote_theme: just-the-docs/just-the-docs 

baseurl: "/Splunk-Cyences-App-for-Splunk"
url: "https://CrossRealms.github.io"

#---

# For local development
# Comment out when deploying 
# theme: just-the-docs

#---

logo: "/assets/cyences-logo.png"

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false


aux_links:
  "Download from Splunkbase":
    - "https://splunkbase.splunk.com/app/5351/"
aux_links_new_tab: true


# color scheme (dark/light)
color_scheme: light


# heading
heading_anchors: true

# footer
footer_content: "Copyright &copy; 2023 CrossRealms International."

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Footer "Edit this page on GitHub" link text
gh_edit_link: false

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  # Custom
  - Dockerfile
  - docker-compose.yml
